# https://stackoverflow.com/questions/35245401/combining-conda-environment-yml-with-pip-requirements-txt
channels:
  - conda-forge
dependencies:
  - mamba
  - python=3.8
  - notebook
  - mamba
  - nbconvert<6  #issue: https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1533
  - jupyter_contrib_nbextensions
  - pyspark>=3.0.1
  - openjdk=11.0.1
  - feature_engine>=1.0.0
  - modin
  - pandas
  - scikit-learn 
  - scikit-plot
  - matplotlib 
  - dataprep
  - psycopg2
  - awscli 
  - boto3
  - s3fs # to read s3 with pandas.
  - awswrangler # To bundle with pandas in reading s3
  - git
  - pip
  - pip:
    - h2o==3.28.0.1
    - jupytext
    - papermill
    - matplotlib
    - seaborn
    - numpy
    - mlflow
