name : datascience
# The first line will be used by dockerfile script. Leave the first line as it is. 
# https://stackoverflow.com/questions/35245401/combining-conda-environment-yml-with-pip-requirements-txt
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab>=3
  - pyspark>=3.0.1
  - openjdk=11.0.1
  - nodejs>=15.3.0
  - scikit-learn 
  - scikit-plot
  - matplotlib 
  - awscli 
  - git
  - pip
  - pip:
    - h2o==3.28.0.1
    - modin>=0.8.3
    - jupytext
    - papermill
    - matplotlib
    - pandas
    - seaborn
    - numpy
    - imblearn # Imbalance learning module.