name : datascience
# The first line will be used by dockerfile script. Leave the first line as it is. 
# https://stackoverflow.com/questions/35245401/combining-conda-environment-yml-with-pip-requirements-txt
channels:
  - conda-forge
dependencies:
  - python=3.8
  # - notebook
  - jupyterlab=3.0.6
  - nbconvert<6  #issue: https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1533
  - jupyter_contrib_nbextensions
  - pyspark>=3.0.1
  - openjdk=11.0.1
  # - nodejs>=15.3.0
  - feature_engine>=1.0.0
  - modin
  - pandas
  - scikit-learn 
  - scikit-plot
  - matplotlib 
  - awscli 
  - git
  - pip
  - pip:
    - h2o==3.28.0.1
    # - modin>=0.8.3
    - jupytext
    - papermill
    - matplotlib
    - seaborn
    - numpy
    - imblearn # Imbalance learning module.